### ISSUE TITLE
Path showing at top of resources

### ISSUE THREAD

**Issue by hugopeek** [Jako/ImagePlus#22] opened 2015-10-13 17:33 UTC
Somehow there is a path showing at the top of the page, just below the menu, pointing to:

/Users/Hugo/Localhost/ctmeter/core/components/imageplus/elements/tv/output/

Really weird, came out of nowhere.. Image+ seems to be working as it should and uninstalling it fixes the problem until you reinstall it again. Also cleared cache manually. Error log remains empty.

![screen shot 2015-10-13 at 21 21 42](https://cloud.githubusercontent.com/assets/5436121/10462706/2da01da2-71f1-11e5-808b-78cd26074497.png)

**Comment by hugopeek** [comment] 2015-10-13 17:42
In addition, it seems that some templates without an Image+ tv also have the path, so it's not necessarily tied to Image+ TV attached to that specific resource.

Also, element inspector is showing no errors.

**Comment by Jako** [comment] 2015-10-14 11:16
I have seen that already on another installation. As far as I remember, it could be caused by an invalid image+ tv content in a MIGX TV.

https://github.com/Jako/ImagePlus/blob/master/core/components/imageplus/elements/plugins/imageplus.plugin.php#L36 should be the line that creates the output.

**Comment by hugopeek** [comment] 2016-01-16 00:01
Hi Jako,

I still haven't figured this one out, but it's definitely related to MIGX as you say. When I disable the MIGX OnTVInputRenderList and OnTVInputPropertiesList events, the line goes away.

I did notice something in the error log now:
```
[2016-01-15 23:30:28] (ERROR @ /Users/Hugo/Localhost/patternlab/core/components/imageplus/model/imageplus/imageplus.class.php : 244) Recoverable error: Argument 3 passed to ImagePlus::prepareTvValue() must be an instance of modTemplateVar, instance of modFileMediaSource_mysql given, called in /Users/Hugo/Localhost/patternlab/core/components/imageplus/elements/tv/input/imageplus.class.php on line 99 and defined
```

Does that tell you anything?

**Comment by Jako** [comment] 2016-01-16 00:10
The error messages are caused by a different bug. That is fixed with https://github.com/Jako/ImagePlus/commit/57c3fe4a0ad1b99f19581e8792b543849bd603a5 and https://github.com/Jako/ImagePlus/commit/045f4c90ac3b233ffc9be4f1223da7184e6eedd7

**Comment by Jako** [comment] 2016-03-13 18:44
Today @donShakespeare told me that the issue occured with TinyMCEWrapper. Could it be possible that you used that extra in your installation?

**Comment by Jako** [comment] 2016-03-16 10:37
If not, are you using a plugin in OnDocFormPrerender that uses $resource->getTVValue ? This triggers the OnTVOutputRenderList event which causes the output.

**Comment by hugopeek** [comment] 2016-03-16 11:36
Hi Jako,

I am not using TinyMCEwrapper, no.. But I'm using Redactor, which has the OnTVOutputRenderList enabled in the plugin and could very well trigger the output instead. 

I can't find a site now that has the issue (my localhost is down), so I can test what happens if I disable Redactor. Will try that later.

**Comment by hugopeek** [comment] 2016-06-05 05:47
Hi Jako,

Sorry for the long delay. I tried out a few things and narrowed it down to the following:

It seems the output is born from a strange love triangle between MIGX, ContentBlocks and Image+. Disabling either the MIGX or the ContentBlocks plugin will make the line go away.

So: Image+ and MIGX is OK, and Image+ with ContentBlocks is also OK. Image+ with both these plugins enabled is not.

The MIGX plugin fires on the following events:

- OnDocFormPrerender
- OnTVInputPropertiesList
- OnTVInputRenderList

And ContentBlocks on these:

- OnDocFormPrerender
- OnDocFormRender
- OnDocFormSave
- OnFileManagerFileRename

There's nothing happening in the error log. If you can't reproduce it, I can copy a cloud where this is happening and give you access if you want.

**Comment by Jako** [comment] 2016-06-06 08:00
There are four lines with $resource->getTVValue in MIGX for further checking:

https://github.com/Bruno17/MIGX/search?utf8=%E2%9C%93&q=getTVValue

Maybe one of those lines triggers the issue. If yes, the line has to be changed to retrieve the TV value without that method, since the https://github.com/Jako/ImagePlus/blob/5358e2f4aaecbb12165888a75af2535fef5cd5a4/core/components/imageplus/elements/plugins/imageplus.plugin.php#L41 can't be changed in the Image+ code.

**Comment by Jako** [comment] 2016-09-24 16:59
The issue is generated by another extra that calls $resource->getTVValue in the backend. That is not a valid approach because it causes a not wanted event (see https://github.com/Jako/ImagePlus/issues/22#issuecomment-197254849) and should be changed in the other extra.

**Closed by Jako** 2016-09-24 16:59 UTC
Labels: bug

**Comment by Jako** [comment] 2017-04-10 13:03
To locate the extra that is calling the method, insert the following code in `case 'OnTVOutputRenderList':`

```
        die(debug_print_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS));
```
