### ISSUE TITLE
Output type imageplus settings not showing after updating to MODX 2.4

### ISSUE THREAD

**Issue by mdehaan** [Jako/ImagePlus#18] opened 2015-09-17 14:03 UTC
After I upgraded to MODX 2.4 the settings on the imageplus output type don't show up anymore.

**Comment by mdehaan** [comment] 2015-09-17 14:53
After some more testing I found out that there is much more that doesn't work after the MODX update

**Comment by Jako** [comment] 2015-09-17 15:24
Duplicate of #13

**Closed by Jako** 2015-09-17 15:24 UTC
