### ISSUE TITLE
Image too small

### ISSUE THREAD

**Issue by menegain** [Jako/ImagePlus#67] opened 2017-12-05 14:26 UTC
Hi,
Image+ say: "Image too small" when i select a image with width and height superior of my input with parameters target Width 1280px and Height 720px. I noticed that problem exists when we put targetwidth higher than 800px. I can see also that at the moment I have the error message, I have a sw to 800 that is sent but my image has 4000px wide.

CMS : modx 2.6.0-pl
Installed extensions : 

- Image+ 2.7.0-pl
- pThumb 2.3.3-pl
- resizer 1.0.1-pl

Image test size : 4000 x 2666

Screenshot TV parameter : [http://hpics.li/32fec2e](http://hpics.li/32fec2e)
Screenshot console network : [http://hpics.li/150e10d](http://hpics.li/150e10d)

**Comment by Jako** [comment] 2017-12-05 20:23
Duplicate of #62

**Closed by Jako** 2017-12-05 20:23 UTC
