### ISSUE TITLE
Empty template variable create error in log

### ISSUE THREAD

**Issue by thorjoel** [Jako/ImagePlus#39] opened 2016-05-27 11:58 UTC
MODX Revolution: 2.5.0
imageplus: 2.4.3-pl

The error below is outputted in the error log on every call to a imageplus template variable that is empty. It fills up the error-log rapidly on one of our big sites.

[2016-05-27 13:21:38] (ERROR in Image+ @ /....../web/core/components/imageplus/model/cropengines/PhpThumbOf.php : 53) The value is empty. Could not prepare the output.

**Comment by Jako** [comment] 2016-05-27 12:25
Duplicate of #33

**Closed by Jako** 2016-05-27 12:25 UTC
