### ISSUE TITLE
Only shows top left of image in the ImagePlus TV.

### ISSUE THREAD

**Issue by digitalpenguin** [Jako/ImagePlus#66] opened 2017-11-23 07:46 UTC
MODX 2.6.0 and ImagePlus 2.7.0 
When selecting new image in an ImagePlus TV, only the top left of the image is shown. Cropping can adjust the height of the image but not the area that's selected.

As you can see in the image the crop shows a different selected area to what the TV image preview does.
![screenshot from 2017-11-23 15-42-30](https://user-images.githubusercontent.com/5160368/33162581-380531fe-d065-11e7-88db-d7bc103ce91a.png)

Just the top left of the image goes through to the web context too.

**Comment by Jako** [comment] 2017-11-23 07:47
Should be a duplicate of #62

**Closed by Jako** 2017-11-23 07:47 UTC

**Comment by digitalpenguin** [comment] 2017-11-23 07:48
Ah sorry. Thanks @Jako
