### ISSUE TITLE
Revo 2.6.0 with ImagePlus = cropping problem

### ISSUE THREAD

**Issue by rainbowtiger** [Jako/ImagePlus#64] opened 2017-11-20 20:50 UTC
After upgrading to 2.6.0, the cropping feature in ImagePlus does a weird thing: the photos are all zoomed way in from where the crop is supposed to be, even when leaving the full image there with no cropping. The cropping shows up properly in the popup window where you apply the cropping, but the thumbnail that shows up in the resource editing screen (and the image on the front end) are zoom-cropped in.
![cropping-popup](https://user-images.githubusercontent.com/2528374/33041293-d7dcb988-ce0b-11e7-90d7-46032755ffd5.png)
![back-in-resource](https://user-images.githubusercontent.com/2528374/33041299-dba852ac-ce0b-11e7-933b-b6e0fef2f819.png)

**Comment by johnmacdonald3000** [comment] 2017-11-21 03:15
I have a similar problem. It's a bit inconvenient but it usually works okay the second time you crop.

**Comment by rainbowtiger** [comment] 2017-11-21 03:39
That doesn't work for me. It happens every time.

**Comment by Jako** [comment] 2017-11-21 08:01
Duplicate of #62

**Closed by Jako** 2017-11-21 08:01 UTC
